// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';
import {model} from '../models';

export function AddToBookshelf(arg1:storage.BookshelfEntry):Promise<number>;

export function GetBookshelf():Promise<Array<storage.BookshelfEntry>>;

export function GetCacheStats():Promise<Record<string, main.CacheStats>>;

export function GetChapterContent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<model.ChapterContent>;

export function GetChapters(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<model.Chapter>>;

export function GetHotBooks():Promise<Array<model.Book>>;

export function GetProgress(arg1:string):Promise<storage.ReadingProgress>;

export function GetSetting(arg1:string):Promise<string>;

export function RemoveFromBookshelf(arg1:number):Promise<void>;

export function SearchBooks(arg1:string,arg2:string):Promise<Array<model.Book>>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateProgress(arg1:string,arg2:number,arg3:string):Promise<void>;
