// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChapterContent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetChapterContent'](arg1, arg2, arg3, arg4, arg5);
}

export function GetChapters(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetChapters'](arg1, arg2, arg3, arg4);
}

export function GetHotBooks() {
  return window['go']['main']['App']['GetHotBooks']();
}

export function SearchBooks(arg1, arg2) {
  return window['go']['main']['App']['SearchBooks'](arg1, arg2);
}
