// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToBookshelf(arg1) {
  return window['go']['main']['App']['AddToBookshelf'](arg1);
}

export function GetBookshelf() {
  return window['go']['main']['App']['GetBookshelf']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetChapterContent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetChapterContent'](arg1, arg2, arg3, arg4, arg5);
}

export function GetChapters(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetChapters'](arg1, arg2, arg3, arg4);
}

export function GetHotBooks() {
  return window['go']['main']['App']['GetHotBooks']();
}

export function GetProgress(arg1) {
  return window['go']['main']['App']['GetProgress'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function RemoveFromBookshelf(arg1) {
  return window['go']['main']['App']['RemoveFromBookshelf'](arg1);
}

export function SearchBooks(arg1, arg2) {
  return window['go']['main']['App']['SearchBooks'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function UpdateProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProgress'](arg1, arg2, arg3);
}
