// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetChapterContent(arg1:string,arg2:string):Promise<model.ChapterContent>;

export function GetChapters(arg1:string):Promise<Array<model.Chapter>>;

export function GetHotBooks():Promise<Array<model.Book>>;

export function SearchBooks(arg1:string,arg2:string):Promise<Array<model.Book>>;
